# Generated by Django 5.1.3 on 2024-12-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_encoding',
            field=models.BinaryField(default=b''),
        ),
    ]
